var defects={};
defects[1]={"title":"Стеклянная нить", "level":"3",};
defects[2]={"title":"Cлед от плунжера", "level":"3"};
defects[3]={"title":"Прилип стекла внутри бутылки", "level":"3"};
defects[4]={"title":"Прилеп(стекло прилипшее снаружи)", "level":"3"};
defects[5]={"title":"Бой на лере", "level":"3"};
defects[6]={"title":"Осевая нагрузка", "level":"3"};



defects[110]={"title":"Подпрессовка", "level":"2"};
defects[111]={"title":"Плохой отжиг", "level":"2"};
defects[112]={"title":"Инородное включение с посечками", "level":"2"};
defects[113]={"title":"Скол (Щербины)", "level":"2"};
defects[114]={"title":"Недопресовка", "level":"2"};
defects[115]={"title":"Внутренний диаметр горла (min)", "level":"2"};
defects[116]={"title":"Тонкая стенка", "level":"2", "count":"yes"};
defects[117]={"title":"Тонкое дно", "level":"2", "count":"yes"};
defects[118]={"title":"Посечка по венчику", "level":"2"};
defects[119]={"title":"Посечка по горлу", "level":"2"};
defects[120]={"title":"Посечка по дну", "level":"2"};
defects[121]={"title":"Посечка по корпусу", "level":"2"};
defects[122]={"title":"Посечка по плечикам", "level":"2"};
defects[123]={"title":"Посечка по резьбе", "level":"2"};
defects[124]={"title":"Посечка под венчиком", "level":"2"};
defects[125]={"title":"Посечка торцевидная", "level":"2"};
defects[126]={"title":"Внутреннее гидравлическое давление", "level":"2", "count":"yes"};
defects[127]={"title":"Ударная прочность", "level":"2"};
defects[128]={"title":"Термостойкойсть", "level":"2"};
defects[129]={"title":"Пузырь открытый на внутренней поверхности", "level":"2"};
defects[130]={"title":"Острый шов, острое горло", "level":"2"};
defects[131]={"title":"Залив дна", "level":"2"};
defects[132]={"title":"Диаметр венчика над резьбой", "level":"2"};
defects[133]={"title":"Диаметр по резьбе", "level":"2"};
defects[134]={"title":"Общая высота", "level":"2"};
defects[135]={"title":"Забой по венчику", "level":"2"};
defects[136]={"title":"Полная вместимость", "level":"2"};
defects[137]={"title":"Забой формы", "level":"2"};



defects[200]={"title":"LOF", "level":"1"};
defects[201]={"title":"След отреза ножниц", "level":"1"};
defects[202]={"title":"Номинальная вместимость", "level":"1", "count":"yes"};
defects[203]={"title":"Инородное включение", "level":"1"};
defects[204]={"title":"Пузырь больше допуска(по СП)", "level":"1"};
defects[205]={"title":"Свиль", "level":"1"};
defects[206]={"title":"Грубый шов", "level":"1"};
defects[207]={"title":"Двойной шов, втянутый", "level":"1"};
defects[208]={"title":"Деформация корпуса", "level":"1"};
defects[209]={"title":"Забитый шов", "level":"1"};
defects[210]={"title":"Заусенец", "level":"1"};
defects[211]={"title":"Кованность, неравномерное распределение стекла", "level":"1"};
defects[212]={"title":"Гладкий кольцевой шов", "level":"1"};
defects[213]={"title":"Морщины", "level":"1"};
defects[214]={"title":"Мошка", "level":"1"};
defects[215]={"title":"Непропечатка логотипа, рисунка и насечек", "level":"1"};
defects[216]={"title":"Несмываемые загрязнения", "level":"1"};
defects[217]={"title":"Складка", "level":"1"};
defects[218]={"title":"След смазки, грязная форма", "level":"1"};
defects[219]={"title":"Смещение полуформ", "level":"1"};
defects[220]={"title":"Смещенное дно (выход)", "level":"1"};
defects[221]={"title":"Уголки", "level":"1"};
defects[222]={"title":"Шероховатость, след от формы", "level":"1"};
defects[223]={"title":"Плоскостность", "level":"1"};
defects[224]={"title":"Вогнутость торца венчика", "level":"1", "count":"yes"};
defects[225]={"title":"Габаритный диаметр/размер корпуса", "level":"1", "count":"yes"};
defects[226]={"title":"Диаметр/размер корпуса по этикеточному полю", "level":"1", "count":"yes"};
defects[227]={"title":"Деформация венчика", "level":"1"};
defects[228]={"title":"Деформация горла", "level":"1"};
defects[229]={"title":"Деформация резьбы", "level":"1"};
defects[230]={"title":"Залив горла", "level":"1"};
defects[231]={"title":"Внутренний диаметр венчика на глубине", "level":"1", "count":"yes"};
defects[232]={"title":"Диаметр укрепляющего кольца", "level":"1", "count":"yes"};
defects[233]={"title":"Диаметр укупорочного кольца", "level":"1", "count":"yes"};
defects[234]={"title":"Сдвиг горловины", "level":"1"};
defects[235]={"title":"Отклонение от вертикальной оси", "level":"1"};
defects[236]={"title":"Отклонение от параллельной плоскости", "level":"1", "count":"yes"};
defects[237]={"title":"Избыточное горячее напыление (иризация)", "level":"1"};
defects[238]={"title":"Избыточное холодное напыление (потеки)", "level":"1"};
defects[239]={"title":"Нет горячего напыления", "level":"1"};
defects[240]={"title":"Нет холодного напыления", "level":"1"};
defects[241]={"title":"Овальность", "level":"1"};
defects[242]={"title":"Рваная складка", "level":"1"};
defects[243]={"title":"Простой", "level":"1"};
defects[244]={"title":"Сброс годной на И. О.", "level":"1"};
defects[245]={"title":"Неустойчивость", "level":"1"};

var corrective_actions={}
corrective_actions[0]={title:"Норма", color:"#0F0", lvl:0, cellClass:"norma"};
corrective_actions[1]={title:"Предупреждение", color:"#999999", lvl:1, cellClass:"grey"};
corrective_actions[2]={title:"Сброс ИО и Визуал", color:"yellow", lvl:2, cellClass:"yellow"};
corrective_actions[3]={title:"MNR", color:"red", lvl:3, cellClass:"red"};

var months={}
months[1]={"name":"янв","days":31};
months[2]={"name":"фев","days":29};
months[3]={"name":"мар","days":31};
months[4]={"name":"апр","days":30};
months[5]={"name":"май","days":31};
months[6]={"name":"июн","days":30};
months[7]={"name":"июл","days":31};
months[8]={"name":"авг","days":31};
months[9]={"name":"сен","days":30};
months[10]={"name":"окт","days":31};
months[11]={"name":"ноя","days":30};
months[12]={"name":"дек","days":31};
